packages:
  - 'packages/**'
  - 'tooling/**'

catalogs:
  dev:
    '@pixpilot/dev-config': ^3.22.0
    '@types/node': ^25.6.2
    '@vitest/coverage-v8': ^4.1.5
    '@vitest/ui': ^4.1.5
    eslint: ^10.10.0
    glob: ^13.0.6
    prettier: ^3.9.6
    tsdown: ^0.23.0
    typescript: ^5.9.3
    vitest: ^4.1.5
    unrun: ^0.3.1

overrides:
  '@types/node': catalog:dev
