packages:
  - 'packages/**'
  - 'tooling/**'

catalogs:
  dev:
    '@changesets/cli': ^2.31.1
    '@commitlint/cli': ^21.2.3
    '@commitlint/config-conventional': ^21.2.3
    '@pixpilot/dev-config': ^3.22.1
    '@pixpilot/eslint-config': ^3.0.0
    '@pixpilot/tsdown-config': ^0.8.3
    '@pixpilot/workspace-package-generator': ^2.1.2
    '@types/node': ^26.6.3
    '@vitest/coverage-v8': ^5.0.3
    '@vitest/ui': ^5.0.3
    eslint: ^10.11.0
    glob: ^13.0.6
    husky: ^9.1.7
    lint-staged: ^17.6.0
    prettier: ^3.9.9
    rimraf: ^6.1.3
    tsdown: ^0.23.0
    tsx: ^4.23.15
    turbo: ^2.11.5
    typescript: ^6.0.3
    vitest: ^5.0.3
    unrun: ^0.3.1

overrides:
  '@types/node': catalog:dev
